# Generated by Django 4.2.5 on 2024-03-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='campaign_id',
            field=models.CharField(choices=[('CUST_ID', 'CUST_ID'), ('SEX', 'SEX')], default='CUST_ID', max_length=10),
        ),
    ]
