# Generated by Django 4.2.5 on 2024-03-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=420, null=True),
        ),
    ]
